model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm_tev.LatentDiffusion
  params:
    load_only_unet: True
    tevloss_weight_rec: 50
    tevloss_weight_tev: 50
    pixel_tev: true
    vnums: 4
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: conditional
    image_size: 64
    channels: 4
    concat_mode: true
    monitor: val/loss_simple_ema
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 7
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_head_channels: 8
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: "./pretrained/vqf8_pretrained/model.ckpt"
        embed_dim: 4
        n_embed: 16384
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: 
          - 32
          dropout: 0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescaler
      params:
        n_stages: 3
        method: bicubic
        in_channels: 3
        out_channels: 3
    tev_net_config: 
      target: ldm.modules.HADARNet.modules.HADARNet
      params:
        in_channels: 3
        out_channels: 6
        smp_model: Unet
        smp_encoder: resnet18
        ckpt_path: "./pretrained/TeVNet_KAIST/epoch_950.pth"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.kaist512.KAISTTrain
      params:
        size: 512
    validation:
      target: ldm.data.kaist512.KAISTVal
      params:
        size: 512
